name: Site Published

on:
  page_build

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Show changed files
        run: |
          cat $GITHUB_EVENT_PATH
          echo ""
          echo Commit: $(jq -r ".build.commit" $GITHUB_EVENT_PATH)
          echo "git-show output"
          git show --pretty="" --name-only --diff-filter=A $(jq -r ".build.commit" $GITHUB_EVENT_PATH)
          echo "git-diff-tree output"
          git diff-tree --no-commit-id --name-only --diff-filter=A -r $(jq -r ".build.commit" $GITHUB_EVENT_PATH)
          echo "end."
