name: Github Pages

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.69.2'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

  notify:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Show changed files
        run: |
          cat $GITHUB_EVENT_PATH
          echo ""
          echo Commit: $(jq -r ".build.commit" $GITHUB_EVENT_PATH)
          echo "git-show output"
          git show --pretty="" --name-only --diff-filter=A $(jq -r ".build.commit" $GITHUB_EVENT_PATH)
          echo "git-diff-tree output"
          git diff-tree --no-commit-id --name-only --diff-filter=A -r $(jq -r ".build.commit" $GITHUB_EVENT_PATH)
          echo "end."
