name: Github Pages

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.69.2'

      - name: Build
        run: hugo --minify

      - name: Deploy
        id: deploy-hugo
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Show output precent step
        run: |
          echo ${{ steps.deploy-hugo.outputs }}

      - name: Set deploy commit hash
        id: deploy-commit
        run: |
          sha=$(git log --grep="$GITHUB_SHA" --pretty="%H" -n 1)
          echo ::set-output name=sha::$sha


  notify:
    runs-on: ubuntu-18.04
    needs: deploy
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Show changed files
        run: |
          # cat $GITHUB_EVENT_PATH
          # echo ${{ jobs.deploy.steps.deploy-commit.outputs.sha }}
          echo ""
          echo Commit: $GITHUB_SHA
          echo "git-show output"
          git show --pretty="" --name-only --diff-filter=A $(git log --grep=$GITHUB_SHA --pretty="%H")
          echo "git-diff-tree output"
          git diff-tree --no-commit-id --name-only --diff-filter=A -r $(git log --grep=$GITHUB_SHA --pretty="%H")
          echo "end."
