name: Github Pages

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-18.04
    outputs:
      dst_sha: ${{ steps.pages.outputs.dst_sha }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.69.2'

      - name: Build
        run: hugo --minify

      - name: Deploy
        id: pages
        uses: peaceiris/actions-gh-pages@7e55c73 #514
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Show output precent step
        if: steps.pages.outputs.dst_sha
        run: |
          echo ${{ steps.pages.outputs.dst_sha }}


  notify:
    runs-on: ubuntu-18.04
    needs: deploy
    if: needs.deploy.outputs.dst_sha
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Show changed files
        id: new-content
        run: |
          echo ${{ needs.deploy.outputs.dst_sha }}
          json_post=$(./bin/extract_post.sh ${{ needs.deploy.outputs.dst_sha }})
          echo ::set-output name=json-post::$json_post

      - name: Post on Twitter
        run: |
          ./bin/post_twitter.py ${{ steps.new-content.outputs.json-post }}
